// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {jira} from '../models';
import {jirahelper} from '../models';
import {context} from '../models';

export function GetBoards():Promise<Array<jira.Board>>;

export function IssueDetails(arg1:string):Promise<jira.Issue>;

export function LogOut():void;

export function RetrieveDashboardsForProjectCached(arg1:string):Promise<Array<jira.Board>>;

export function RetrieveProjects():Promise<jira.ProjectList>;

export function RetrieveSprintsForBoard(arg1:string):Promise<Array<jira.Sprint>>;

export function GetBoardsCached():Promise<Array<jira.Board>>;

export function RetrieveSprint(arg1:number):Promise<Array<jira.Issue>>;

export function IsAuthenticated():Promise<boolean>;

export function RetrieveBoardDetailsCached(arg1:number):Promise<jira.Board>;

export function RetrieveProjectCached(arg1:string):Promise<jira.Project>;

export function RetrieveProjectsCached():Promise<jira.ProjectList>;

export function RetrieveSprintCached(arg1:number):Promise<Array<jira.Issue>>;

export function SearchIssues(arg1:string):Promise<Array<jira.Issue>>;

export function ShutDown():void;

export function AuthenticateReal(arg1:jirahelper.LoginCredentials):void;

export function IssueDetailsCached(arg1:string):Promise<jira.Issue>;

export function RetrieveBoardDetails(arg1:number):Promise<jira.Board>;

export function RetrieveDashboardsForProject(arg1:string):Promise<Array<jira.Board>>;

export function RetrieveProject(arg1:string):Promise<jira.Project>;

export function RetrieveSprintsForBoardCached(arg1:string):Promise<Array<jira.Sprint>>;

export function Startup(arg1:context.Context):void;

export function TryLoggingWithPreviousCredentials():void;
