// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateReal(arg1) {
  return window['go']['jirahelper']['JiraHelper']['AuthenticateReal'](arg1);
}

export function GetBoards() {
  return window['go']['jirahelper']['JiraHelper']['GetBoards']();
}

export function GetBoardsCached() {
  return window['go']['jirahelper']['JiraHelper']['GetBoardsCached']();
}

export function IsAuthenticated() {
  return window['go']['jirahelper']['JiraHelper']['IsAuthenticated']();
}

export function IssueDetails(arg1) {
  return window['go']['jirahelper']['JiraHelper']['IssueDetails'](arg1);
}

export function IssueDetailsCached(arg1) {
  return window['go']['jirahelper']['JiraHelper']['IssueDetailsCached'](arg1);
}

export function LogOut() {
  return window['go']['jirahelper']['JiraHelper']['LogOut']();
}

export function RetrieveBoardDetails(arg1) {
  return window['go']['jirahelper']['JiraHelper']['RetrieveBoardDetails'](arg1);
}

export function RetrieveBoardDetailsCached(arg1) {
  return window['go']['jirahelper']['JiraHelper']['RetrieveBoardDetailsCached'](arg1);
}

export function RetrieveDashboardsForProject(arg1) {
  return window['go']['jirahelper']['JiraHelper']['RetrieveDashboardsForProject'](arg1);
}

export function RetrieveDashboardsForProjectCached(arg1) {
  return window['go']['jirahelper']['JiraHelper']['RetrieveDashboardsForProjectCached'](arg1);
}

export function RetrieveProject(arg1) {
  return window['go']['jirahelper']['JiraHelper']['RetrieveProject'](arg1);
}

export function RetrieveProjectCached(arg1) {
  return window['go']['jirahelper']['JiraHelper']['RetrieveProjectCached'](arg1);
}

export function RetrieveProjects() {
  return window['go']['jirahelper']['JiraHelper']['RetrieveProjects']();
}

export function RetrieveProjectsCached() {
  return window['go']['jirahelper']['JiraHelper']['RetrieveProjectsCached']();
}

export function RetrieveSprint(arg1) {
  return window['go']['jirahelper']['JiraHelper']['RetrieveSprint'](arg1);
}

export function RetrieveSprintCached(arg1) {
  return window['go']['jirahelper']['JiraHelper']['RetrieveSprintCached'](arg1);
}

export function RetrieveSprintsForBoard(arg1) {
  return window['go']['jirahelper']['JiraHelper']['RetrieveSprintsForBoard'](arg1);
}

export function RetrieveSprintsForBoardCached(arg1) {
  return window['go']['jirahelper']['JiraHelper']['RetrieveSprintsForBoardCached'](arg1);
}

export function SearchIssues(arg1) {
  return window['go']['jirahelper']['JiraHelper']['SearchIssues'](arg1);
}

export function ShutDown() {
  return window['go']['jirahelper']['JiraHelper']['ShutDown']();
}

export function Startup(arg1) {
  return window['go']['jirahelper']['JiraHelper']['Startup'](arg1);
}

export function TryLoggingWithPreviousCredentials() {
  return window['go']['jirahelper']['JiraHelper']['TryLoggingWithPreviousCredentials']();
}
