// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBoards() {
  return window['go']['main']['App']['GetBoards']();
}

export function GetFavourites() {
  return window['go']['main']['App']['GetFavourites']();
}

export function IssueDetails(arg1) {
  return window['go']['main']['App']['IssueDetails'](arg1);
}

export function RetrieveBoardDetails(arg1) {
  return window['go']['main']['App']['RetrieveBoardDetails'](arg1);
}

export function SearchIssues(arg1) {
  return window['go']['main']['App']['SearchIssues'](arg1);
}

export function AuthenticateReal(arg1) {
  return window['go']['main']['App']['AuthenticateReal'](arg1);
}

export function RetrieveProjects() {
  return window['go']['main']['App']['RetrieveProjects']();
}

export function RetrieveProjectsCached() {
  return window['go']['main']['App']['RetrieveProjectsCached']();
}

export function LogOut() {
  return window['go']['main']['App']['LogOut']();
}

export function GetBoardsCached() {
  return window['go']['main']['App']['GetBoardsCached']();
}

export function RetrieveDashboardsForProject(arg1) {
  return window['go']['main']['App']['RetrieveDashboardsForProject'](arg1);
}

export function RetrieveDashboardsForProjectCached(arg1) {
  return window['go']['main']['App']['RetrieveDashboardsForProjectCached'](arg1);
}

export function RetrieveProject(arg1) {
  return window['go']['main']['App']['RetrieveProject'](arg1);
}

export function RetrieveSprintsForBoard(arg1) {
  return window['go']['main']['App']['RetrieveSprintsForBoard'](arg1);
}

export function AddFavourite(arg1, arg2) {
  return window['go']['main']['App']['AddFavourite'](arg1, arg2);
}

export function IssueDetailsCached(arg1) {
  return window['go']['main']['App']['IssueDetailsCached'](arg1);
}

export function RemoveFavourite(arg1) {
  return window['go']['main']['App']['RemoveFavourite'](arg1);
}

export function RetrieveBoardDetailsCached(arg1) {
  return window['go']['main']['App']['RetrieveBoardDetailsCached'](arg1);
}

export function RetrieveProjectCached(arg1) {
  return window['go']['main']['App']['RetrieveProjectCached'](arg1);
}

export function RetrieveSprint(arg1) {
  return window['go']['main']['App']['RetrieveSprint'](arg1);
}

export function RetrieveSprintCached(arg1) {
  return window['go']['main']['App']['RetrieveSprintCached'](arg1);
}

export function RetrieveSprintsForBoardCached(arg1) {
  return window['go']['main']['App']['RetrieveSprintsForBoardCached'](arg1);
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function TryLoggingWithPreviousCredentials() {
  return window['go']['main']['App']['TryLoggingWithPreviousCredentials']();
}
