// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavourite(arg1, arg2) {
  return window['go']['main']['App']['AddFavourite'](arg1, arg2);
}

export function GetFavourites() {
  return window['go']['main']['App']['GetFavourites']();
}

export function RemoveFavourite(arg1) {
  return window['go']['main']['App']['RemoveFavourite'](arg1);
}
