// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavourite(arg1:string,arg2:string):void;

export function GetFavourites():Promise<any>;

export function RemoveFavourite(arg1:string):void;
